### PR TITLE
Remove pre-prod disclaimer

### PR DESCRIPTION
**Pull request by gksander**
This PR removes pre-prod disclaimer, and has install instructions of `yarn add victory-native` (instead of `victory-native@next`).

### CODE REVIEW

**Review by carloskelly13 — COMMENTED** [review]
Do we wanna remove the banner from the docs too?

**Comment by gksander** [comment]
I was thinking we'd leave that banner at least temporarily since I suspect we'll still have plenty of users using version <40.

**Comment by carloskelly13** [comment]
Let's also update `introduction.md` as it mentions "pre-release" 

Screenshot 2023-10-03 at 5 12 00 AM

**Review by carloskelly13 — APPROVED** [review]
Just one additional instance of "beta" / "pre-release" found and I think this is good to merge after that!

**Pull request merged**
